# Generated by Django 6.0.7 on 2026-07-24 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
    ]
