# Generated by Django 6.0.7 on 2026-08-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_content_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['created_at'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
