# Generated by Django 6.0.7 on 2026-08-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_content_app', '0003_remove_video_thumbnail_url_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
