# Generated by Django 6.0.7 on 2026-08-12 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_content_app', '0004_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.RemoveField(
            model_name='video',
            name='hls_path',
        ),
    ]
